#!/usr/bin/env node
/**
 * JavaScript/TypeScript File Splitter v1.1
 * 智能拆分JS/TS文件，确保每个文件 ≤ 19KB
 * 支持：ES6模块、CommonJS、React组件、Vue SFC、压缩单行JS
 *
 * v1.1 修复：
 *  - 添加备份机制（操作前先备份原文件）
 *  - 支持压缩单行JS解析（通过 prettier 格式化后分析）
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const MAX_SIZE = 19 * 1024; // 19KB

// ============================================================================
// 工具函数
// ============================================================================

/**
 * 尝试用 prettier 格式化压缩JS，使其可分析
 */
function tryFormatWithPrettier(code) {
  // 检测是否为压缩单行JS（行数少但文件大，或包含大量连续数据）
  const lines = code.split('\n');
  const isMinified = lines.length < 5 && code.length > 50000;

  if (!isMinified) return code;

  try {
    // 尝试用 prettier 格式化
    const formatted = execSync(
      'npx prettier --stdin-filepath input.js',
      { input: code, encoding: 'utf-8', timeout: 10000 }
    );
    return formatted;
  } catch (e) {
    // prettier 不可用，尝试手动格式化
    return manualFormatMinified(code);
  }
}

/**
 * 手动格式化压缩JS（备选方案）
 * 策略：将长语句按分号拆分，缩进花括号块
 */
function manualFormatMinified(code) {
  let result = '';
  let i = 0;
  let indent = 0;
  let buffer = '';

  while (i < code.length) {
    const ch = code[i];

    // 遇到字符串，复制到 buffer
    if (ch === '"' || ch === "'" || ch === '`') {
      const quote = ch;
      buffer += ch;
      i++;
      while (i < code.length) {
        const c = code[i];
        buffer += c;
        if (c === quote && code[i - 1] !== '\\') break;
        i++;
      }
      i++;
      continue;
    }

    // 花括号处理
    if (ch === '{') {
      buffer += ' {\n' + '  '.repeat(++indent);
      i++;
      continue;
    }
    if (ch === '}') {
      indent = Math.max(0, indent - 1);
      buffer += '\n' + '  '.repeat(indent) + '}';
      i++;
      // 分号换行
      if (code[i] === ';') {
        buffer += ';';
        i++;
      }
      buffer += '\n' + '  '.repeat(indent);
      continue;
    }

    // 遇到分号，换行
    if (ch === ';') {
      buffer += ';\n' + '  '.repeat(indent);
      i++;
      continue;
    }

    buffer += ch;
    i++;
  }

  return buffer.trim();
}

/**
 * 检测是否为可自动生成的图表绑定文件（如 Plotly/Chart.js 自动生成）
 * 这类文件拆分后会破坏功能，应该警告用户
 */
function detectAutoGeneratedChart(code) {
  const markers = [
    /new\s+Chart\s*\(/i,
    /Plotly\.newPlot/i,
    /google\.charts\.load/i,
    /echarts\.init/i,
    /var\s+\w+=\[.*\]\s*;.*new\s+Chart/i,  // 数据数组 + Chart 模式
  ];

  const score = markers.filter(m => m.test(code)).length;
  // 数据数组（长数字数组）+ Chart 调用 = 高度疑似自动生成
  const hasLargeDataArray = /\[\s*[\d.,\s]{200,}\]\s*;/.test(code);

  return score >= 1 || (score >= 1 && hasLargeDataArray);
}

/**
 * 检测压缩单行JS（用于分析前的预处理）
 */
function detectMinifiedJS(code) {
  const lines = code.split('\n');
  // 单行且超大，或多行但每行超长
  return (lines.length <= 3 && code.length > 30000) ||
         (lines.every(l => l.length > 2000));
}

// ============================================================================
// 主拆分器类
// ============================================================================

class JSFileSplitter {
  constructor(inputFile, outputDir = 'modules', options = {}) {
    this.inputFile = inputFile;
    this.outputDir = outputDir;
    this.options = {
      maxSizeKB: 19,
      moduleType: 'esm',
      framework: 'vanilla',
      skipBackup: false,
      force: false,
      ...options
    };
    this.modules = [];
    this.sourceCode = '';
    this.formattedCode = '';
    this.backupPath = null;
    this.isMinified = false;
  }

  // ===========================================================================
  // 备份管理
  // ===========================================================================

  /**
   * 备份原文件
   * @returns {string} 备份文件路径
   */
  backup() {
    if (this.options.skipBackup) return null;
    if (!fs.existsSync(this.inputFile)) return null;

    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    const ext = path.extname(this.inputFile);
    const base = path.basename(this.inputFile, ext);
    const dir = path.dirname(this.inputFile);
    this.backupPath = path.join(dir, `${base}.${timestamp}.backup${ext}`);

    fs.copyFileSync(this.inputFile, this.backupPath);
    return this.backupPath;
  }

  /**
   * 恢复备份
   */
  restoreBackup() {
    if (this.backupPath && fs.existsSync(this.backupPath)) {
      fs.copyFileSync(this.backupPath, this.inputFile);
      console.log(`  ↩️  已恢复备份: ${this.backupPath}`);
      // 保留备份文件，不删除
    }
  }

  /**
   * 清理旧备份（同一文件的旧备份只保留最新3个）
   */
  cleanOldBackups() {
    const dir = path.dirname(this.inputFile);
    const base = path.basename(this.inputFile, path.extname(this.inputFile));
    const ext = path.extname(this.inputFile);

    const files = fs.readdirSync(dir)
      .filter(f => f.startsWith(base) && f.includes('.backup') && f.endsWith(ext))
      .map(f => ({
        name: f,
        path: path.join(dir, f),
        mtime: fs.statSync(path.join(dir, f)).mtime
      }))
      .sort((a, b) => b.mtime - a.mtime);

    // 只保留最新3个备份
    files.slice(3).forEach(f => {
      try { fs.unlinkSync(f.path); } catch (e) {}
    });
  }

  // ===========================================================================
  // 主拆分流程
  // ===========================================================================

  split() {
    if (!fs.existsSync(this.inputFile)) {
      console.error(`❌ 文件不存在: ${this.inputFile}`);
      return false;
    }

    const resolvedInput = path.resolve(this.inputFile);
    this.sourceCode = fs.readFileSync(resolvedInput, 'utf-8');
    const originalSize = Buffer.byteLength(this.sourceCode, 'utf8');

    console.log('\n============================================================');
    console.log('🔄 JavaScript/TypeScript 文件拆分器 v1.1');
    console.log('============================================================');
    console.log(`📄 输入文件: ${this.inputFile}`);
    console.log(`📁 输出目录: ${this.outputDir}`);
    console.log(`📏 最大文件大小: ${MAX_SIZE} 字节 (${MAX_SIZE / 1024}KB)`);
    console.log('============================================================');
    console.log(`\n📊 源文件大小: ${originalSize} 字节 (${(originalSize / 1024).toFixed(1)}KB)`);

    // ⚠️ 立即备份（在任何分析/检测之前，确保安全）
    const bp = this.backup();
    if (bp) console.log(`\n💾 备份已创建: ${path.basename(bp)}`);

    // Step 0: 检测文件类型
    this.isMinified = detectMinifiedJS(this.sourceCode);
    if (this.isMinified) {
      console.log('📌 检测到: 压缩单行JS，正在尝试格式化...');
      this.formattedCode = tryFormatWithPrettier(this.sourceCode);
      if (this.formattedCode !== this.sourceCode) {
        console.log(`   格式化后: ${Buffer.byteLength(this.formattedCode, 'utf8')} 字节`);
      }
    } else {
      this.formattedCode = this.sourceCode;
    }

    // Step 0.5: 检测是否为自动生成的图表绑定文件
    if (detectAutoGeneratedChart(this.sourceCode)) {
      console.log('\n⚠️  警告: 检测到自动生成的图表绑定文件（Chart.js/Plotly 等）');
      console.log('   这类文件不适合拆分！拆分后会破坏图表绑定逻辑。');
      console.log('   建议: 此类文件应保留原样，或从数据源重新生成。');
      console.log('\n   如需强制拆分，请添加 --force 参数。\n');

      // 检测到图表绑定时：无 --force 则直接退出
      if (!this.options.force) {
        console.log('❌ 已中止。原始文件已备份，安全无忧。');
        console.log(`   恢复命令: 复制 "${path.basename(bp || '')}" → "${this.inputFile}"\n`);
        return false;
      }
      console.log('   已强制执行拆分...\n');
    }

    // Step 1: 分析代码结构
    const analysis = this.analyzeCode();
    console.log('\n📋 代码结构分析:');
    this.printAnalysis(analysis);

    // Step 2: 执行拆分
    console.log('\n🔧 开始拆分...');
    const success = this.executeSplit(analysis);

    // Step 3: 生成报告
    this.printReport(success, originalSize);

    // Step 4: 自动更新 CODE_INDEX.md
    this.updateIndex();

    // Step 6: 清理旧备份
    this.cleanOldBackups();

    return success;
  }

  // ===========================================================================
  // 代码分析（支持多行和单行）
  // ===========================================================================

  analyzeCode() {
    const code = this.formattedCode;
    const analysis = {
      imports: [],
      exports: [],
      functions: [],
      classes: [],
      components: [],
      constants: [],
      topLevelStatements: [],
      size: Buffer.byteLength(code, 'utf8'),
      isMinified: this.isMinified
    };

    if (this.isMinified) {
      return this._analyzeMinifiedCode(analysis, code);
    }
    return this._analyzeStandardCode(analysis, code);
  }

  /**
   * 标准多行JS分析
   */
  _analyzeStandardCode(analysis, code) {
    // 提取 import 语句
    const importRegex = /^import\s+.*?from\s+['"][^'"]+['"]/gm;
    let match;
    while ((match = importRegex.exec(code)) !== null) {
      analysis.imports.push({ code: match[0], start: match.index, end: match.index + match[0].length });
    }

    // 提取 export 语句
    const exportRegex = /^export\s+(default\s+)?(class|function|const|let|var|async)/gm;
    while ((match = exportRegex.exec(code)) !== null) {
      analysis.exports.push({ code: match[0], start: match.index, end: match.index + match[0].length });
    }

    // 提取函数声明
    const funcRegex = /^(export\s+)?(async\s+)?function\s+(\w+)\s*\(/gm;
    while ((match = funcRegex.exec(code)) !== null) {
      const funcName = match[3];
      const funcBody = this.extractBlock(code, match.index);
      analysis.functions.push({
        name: funcName,
        code: funcBody,
        size: Buffer.byteLength(funcBody, 'utf8'),
        start: match.index,
        isExport: match[1] === 'export '
      });
    }

    // 提取箭头函数和函数表达式
    const arrowFuncRegex = /^(export\s+)?const\s+(\w+)\s*=\s*(async\s*)?\(/gm;
    while ((match = arrowFuncRegex.exec(code)) !== null) {
      const funcName = match[2];
      const funcBody = this.extractBlock(code, match.index);
      analysis.functions.push({
        name: funcName,
        code: funcBody,
        size: Buffer.byteLength(funcBody, 'utf8'),
        start: match.index,
        isArrow: true,
        isExport: match[1] === 'export '
      });
    }

    // 提取类声明
    const classRegex = /^(export\s+)?class\s+(\w+)(\s+extends\s+\w+)?\s*{/gm;
    while ((match = classRegex.exec(code)) !== null) {
      const className = match[2];
      const classBody = this.extractBlock(code, match.index);
      const isComponent = this.isComponent(classBody);
      analysis.classes.push({
        name: className,
        code: classBody,
        size: Buffer.byteLength(classBody, 'utf8'),
        start: match.index,
        isComponent,
        isExport: match[1] === 'export '
      });
      if (isComponent) {
        analysis.components.push({ name: className, code: classBody, type: 'class-component' });
      }
    }

    return analysis;
  }

  /**
   * 压缩单行JS分析（按函数/语句分割）
   */
  _analyzeMinifiedCode(analysis, code) {
    // 1. 提取全局变量声明（var/let/const 开头，到分号）
    const varRegex = /(?:var|let|const)\s+(\w+)\s*=/g;
    let match;
    while ((match = varRegex.exec(code)) !== null) {
      const varName = match[1];
      // 提取到对应分号
      const start = match.index;
      let end = start;
      let depth = 0;
      let inStr = false;
      let strChar = '';
      for (let i = start; i < code.length; i++) {
        const c = code[i];
        if (inStr) {
          if (c === strChar && code[i-1] !== '\\') inStr = false;
        } else {
          if (c === '"' || c === "'" || c === '`') { inStr = true; strChar = c; }
          else if (c === '{' || c === '(' || c === '[') depth++;
          else if (c === '}' || c === ')' || c === ']') { if (--depth < 0) break; }
          else if (c === ';' && depth === 0) { end = i + 1; break; }
        }
      }
      const varCode = code.slice(start, end);
      analysis.constants.push({ name: varName, code: varCode, size: Buffer.byteLength(varCode, 'utf8') });
    }

    // 2. 提取 function 声明
    const funcRegex = /function\s+(\w+)\s*\(/g;
    while ((match = funcRegex.exec(code)) !== null) {
      const funcName = match[1];
      const start = match.index;
      let end = start;
      let depth = 0;
      let inStr = false;
      let strChar = '';
      for (let i = start; i < code.length; i++) {
        const c = code[i];
        if (inStr) {
          if (c === strChar && code[i-1] !== '\\') inStr = false;
        } else {
          if (c === '"' || c === "'" || c === '`') { inStr = true; strChar = c; }
          else if (c === '{') depth++;
          else if (c === '}') { if (--depth === 0) { end = i + 1; break; } }
        }
      }
      const funcCode = code.slice(start, end);
      analysis.functions.push({
        name: funcName,
        code: funcCode,
        size: Buffer.byteLength(funcCode, 'utf8'),
        start,
        isMinified: true
      });
    }

    // 3. 提取顶层可执行语句（new Chart(...) / Plotly.newPlot / 顶层调用）
    const execPatterns = [
      /(?:new\s+(?:Chart|Plotly|ECharts|google\.charts\.\w+)\s*\([^;]+);/g,
      /(?:Plotly\.(?:newPlot|react)\s*\([^;]+);/g,
      /(?:document\.(?:getElementById|querySelector)\s*\([^;]+);/g,
    ];
    execPatterns.forEach(pattern => {
      while ((match = pattern.exec(code)) !== null) {
        analysis.topLevelStatements.push({
          code: match[0],
          size: Buffer.byteLength(match[0], 'utf8')
        });
      }
    });

    return analysis;
  }

  // ===========================================================================
  // 代码块提取
  // ===========================================================================

  extractBlock(code, startIndex) {
    let braces = 0;
    let inString = false;
    let stringChar = '';
    let inComment = false;
    let inMultiComment = false;
    let i = startIndex;

    while (i < code.length && /\s/.test(code[i])) i++;

    if (code.slice(i, i + 2) === '//') {
      while (i < code.length && code[i] !== '\n') i++;
      return code.slice(startIndex, i);
    }

    if (code.slice(i, i + 2) === '/*') {
      inMultiComment = true;
      i += 2;
      while (i < code.length - 1) {
        if (code[i] === '*' && code[i + 1] === '/') { i += 2; break; }
        i++;
      }
    }

    while (i < code.length) {
      if (inString) {
        if (code[i] === stringChar && code[i - 1] !== '\\') inString = false;
      } else if (inMultiComment) {
        if (code[i] === '*' && code[i + 1] === '/') { inMultiComment = false; i += 2; continue; }
      } else if (inComment) {
        if (code[i] === '\n') inComment = false;
      } else {
        if (code[i] === '"' || code[i] === "'" || code[i] === '`') {
          inString = true; stringChar = code[i];
        } else if (code[i] === '/' && code[i + 1] === '/') {
          inComment = true;
        } else if (code[i] === '/' && code[i + 1] === '*') {
          inMultiComment = true; i++;
        } else if (code[i] === '{') {
          braces++; break;
        }
      }
      i++;
    }

    if (braces === 0) {
      let end = i;
      while (end < code.length && code[end] !== ';') end++;
      return code.slice(startIndex, end + 1);
    }

    let depth = 1;
    i++;
    while (i < code.length && depth > 0) {
      if (inString) {
        if (code[i] === stringChar && code[i - 1] !== '\\') inString = false;
      } else if (inMultiComment) {
        if (code[i] === '*' && code[i + 1] === '/') { inMultiComment = false; i += 2; continue; }
      } else if (inComment) {
        if (code[i] === '\n') inComment = false;
      } else {
        if (code[i] === '"' || code[i] === "'" || code[i] === '`') {
          inString = true; stringChar = code[i];
        } else if (code[i] === '/' && code[i + 1] === '/') inComment = true;
        else if (code[i] === '/' && code[i + 1] === '*') { inMultiComment = true; i++; }
        else if (code[i] === '{') depth++;
        else if (code[i] === '}') { depth--; if (depth === 0) return code.slice(startIndex, i + 1); }
      }
      i++;
    }

    return code.slice(startIndex, i);
  }

  // ===========================================================================
  // 组件检测
  // ===========================================================================

  isComponent(code) {
    return [
      /return\s*\(/, /return\s*</, /React\.createElement/,
      /useState\s*\(/, /useEffect\s*\(/, /useCallback\s*\(/, /useMemo\s*\(/,
      /defineComponent\s*\(/, /setup\s*\(/, /ref\s*\(/, /reactive\s*\(/, /computed\s*\(/
    ].some(p => p.test(code));
  }

  // ===========================================================================
  // 分析结果输出
  // ===========================================================================

  printAnalysis(analysis) {
    if (analysis.isMinified) {
      analysis.constants.forEach(c => {
        const size = (c.size / 1024).toFixed(1);
        console.log(`  • Const: ${c.name} (${size}KB)`);
      });
      analysis.functions.forEach(f => {
        const size = (f.size / 1024).toFixed(1);
        const warning = f.size > MAX_SIZE ? ' ⚠️ 超限' : '';
        console.log(`  • Function: ${f.name} (${size}KB)${warning}`);
      });
      if (analysis.topLevelStatements.length > 0) {
        console.log(`  • 可执行语句: ${analysis.topLevelStatements.length} 个 (图表绑定等)`);
      }
      console.log(`  ⚠️  压缩单行JS: 将格式化后分析，原始内容完整保留在备份中`);
      return;
    }

    analysis.classes.forEach(cls => {
      const size = (cls.size / 1024).toFixed(1);
      const warning = cls.size > MAX_SIZE ? ' ⚠️ 超限' : '';
      const component = cls.isComponent ? ' [组件]' : '';
      console.log(`  • Class: ${cls.name} (${size}KB)${component}${warning}`);
    });

    analysis.functions.forEach(func => {
      const size = (func.size / 1024).toFixed(1);
      const warning = func.size > MAX_SIZE ? ' ⚠️ 超限' : '';
      console.log(`  • Function: ${func.name} (${size}KB)${warning}`);
    });

    console.log(`  • Imports: ${analysis.imports.length} 个`);
    console.log(`  • Exports: ${analysis.exports.length} 个`);
  }

  // ===========================================================================
  // 执行拆分
  // ===========================================================================

  executeSplit(analysis) {
    if (!fs.existsSync(this.outputDir)) {
      fs.mkdirSync(this.outputDir, { recursive: true });
    }

    let fileIndex = 0;
    const generatedFiles = [];

    // 压缩JS特殊处理：常量、函数、可执行语句各自一个文件
    if (analysis.isMinified) {
      // 全局常量 -> constants.js
      if (analysis.constants.length > 0) {
        const constContent = analysis.constants.map(c => c.code).join('\n');
        const constPath = path.join(this.outputDir, 'constants.js');
        fs.writeFileSync(constPath, constContent, 'utf-8');
        generatedFiles.push({ name: 'constants', type: 'constants', path: constPath });
        console.log(`  ✓ 生成: constants.js`);
      }

      // 函数 -> 各自独立文件
      analysis.functions.forEach(func => {
        const fileName = `${func.name}.js`;
        const filePath = path.join(this.outputDir, fileName);
        fs.writeFileSync(filePath, func.code, 'utf-8');
        this.modules.push({ name: func.name, type: 'function', path: filePath });
        generatedFiles.push({ name: func.name, type: 'function', path: filePath });
        console.log(`  ✓ 生成: ${fileName}`);
      });

      // 可执行语句 -> executable.js
      if (analysis.topLevelStatements.length > 0) {
        const execContent = analysis.topLevelStatements.map(s => s.code).join('\n');
        const execPath = path.join(this.outputDir, 'executable.js');
        fs.writeFileSync(execPath, execContent, 'utf-8');
        generatedFiles.push({ name: 'executable', type: 'executable', path: execPath });
        console.log(`  ✓ 生成: executable.js`);
      }

      // 生成入口文件（保留原始内容）
      this._generateMinifiedEntryFile(generatedFiles);
    } else {
      // 标准多行JS拆分逻辑
      // 1. 组件
      analysis.components.forEach(comp => {
        const fileName = `${this.toKebabCase(comp.name)}.js`;
        const filePath = path.join(this.outputDir, fileName);
        const content = this.wrapWithImports(comp.code, analysis.imports);
        fs.writeFileSync(filePath, content, 'utf-8');
        this.modules.push({ name: comp.name, type: 'component', path: filePath });
        generatedFiles.push({ name: comp.name, type: 'component', path: filePath });
        console.log(`  ✓ 生成: ${fileName}`);
      });

      // 2. 普通类
      analysis.classes.filter(cls => !cls.isComponent).forEach(cls => {
        const fileName = `${this.toKebabCase(cls.name)}.js`;
        const filePath = path.join(this.outputDir, fileName);
        const content = this.wrapWithImports(cls.code, analysis.imports);
        fs.writeFileSync(filePath, content, 'utf-8');
        this.modules.push({ name: cls.name, type: 'class', path: filePath });
        generatedFiles.push({ name: cls.name, type: 'class', path: filePath });
        console.log(`  ✓ 生成: ${fileName}`);
      });

      // 3. 函数
      analysis.functions.forEach(func => {
        const fileName = `${this.toKebabCase(func.name)}.js`;
        const filePath = path.join(this.outputDir, fileName);
        let content = func.isExport ? `export ${func.code}` : func.code;
        content = this.wrapWithImports(content, analysis.imports);
        fs.writeFileSync(filePath, content, 'utf-8');
        this.modules.push({ name: func.name, type: 'function', path: filePath });
        generatedFiles.push({ name: func.name, type: 'function', path: filePath });
        console.log(`  ✓ 生成: ${fileName}`);
      });

      // 4. 聚合适配
      if (generatedFiles.length === 0 || analysis.size < MAX_SIZE) {
        const aggregatedContent = this.aggregateSmallItems(analysis);
        if (aggregatedContent) {
          const filePath = path.join(this.outputDir, 'module_000.js');
          fs.writeFileSync(filePath, aggregatedContent, 'utf-8');
          this.modules.push({ name: 'module_000', type: 'module', path: filePath });
          generatedFiles.push({ name: 'module_000', type: 'module', path: filePath });
          console.log(`  ✓ 生成: module_000.js`);
        }
      }

      // 5. 生成入口文件
      this.generateIndexFile(generatedFiles);
    }

    console.log(`\n  ✓ 生成主文件: index.js`);
    console.log(`  ✓ 生成包初始化: ${this.outputDir}/index.js`);

    return true;
  }

  /**
   * 为压缩JS生成入口文件（保留原始内容作为注释参考）
   */
  _generateMinifiedEntryFile(files) {
    const baseName = path.basename(this.inputFile, path.extname(this.inputFile)) + '.js';
    const mainPath = path.join(path.dirname(this.inputFile) || '.', baseName);

    const imports = files.map(f => {
      const rel = `./${this.outputDir}/${path.basename(f.path, '.js')}`;
      return `import { ${f.name} } from '${rel}';`;
    });

    const exports = files.map(f => `  ${f.name}`);

    let content = [
      '// Auto-generated entry file (compressed JS refactored)',
      `// Source: ${path.basename(this.inputFile)}`,
      '// Generated by js-file-splitter v1.1',
      '// Backup: ' + (this.backupPath ? path.basename(this.backupPath) : 'N/A'),
      '',
      ...imports,
      '',
      'export {',
      exports.join(',\n'),
      '};'
    ].join('\n');

    fs.writeFileSync(mainPath, content, 'utf-8');
    console.log(`  ✅ 生成主文件: ${baseName}`);

    // modules/index.js 同步
    const indexPath = path.join(this.outputDir, 'index.js');
    fs.writeFileSync(indexPath, content, 'utf-8');
  }

  // ===========================================================================
  // 入口文件生成（标准JS）
  // ===========================================================================

  generateIndexFile(files) {
    const mainFileName = path.basename(this.inputFile, path.extname(this.inputFile)) + '.js';
    const mainPath = path.join(path.dirname(this.inputFile) || '.', mainFileName);
    const executableBlock = this.extractExecutableBlock(this.sourceCode);

    const baseImports = files.map(f => {
      const relativePath = `./${this.outputDir}/${path.basename(f.path, '.js')}`;
      return `import { ${f.name} } from '${relativePath}';`;
    });

    const exports = files.map(f => `  ${f.name}`);

    let content = [
      '// Auto-generated entry file',
      `// Source: ${path.basename(this.inputFile)}`,
      '// Generated by js-file-splitter',
      '// Backup: ' + (this.backupPath ? path.basename(this.backupPath) : 'N/A'),
      '',
      ...baseImports,
      '',
      'export {',
      exports.join(',\n'),
      '};'
    ].join('\n');

    if (executableBlock) {
      content += '\n\n' + '// === Original executable code (auto-extracted) ===\n' + executableBlock + '\n';
    }

    fs.writeFileSync(mainPath, content, 'utf-8');
    console.log(`  ✅ 生成主文件: ${mainFileName} (含原始可执行代码)`);

    const indexPath = path.join(this.outputDir, 'index.js');
    fs.writeFileSync(indexPath, content, 'utf-8');
    console.log(`  ✅ 生成包初始化: ${this.outputDir}/index.js`);
  }

  /**
   * 提取可执行代码块
   */
  extractExecutableBlock(sourceCode) {
    const lines = sourceCode.split('\n');
    let executableLines = [];
    let inBlock = false;
    let depth = 0;
    let blockType = null;

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const trimmed = line.trim();

      if (!inBlock) {
        if (/if\s*\(\s*require\.main\s*===\s*module\s*\)\s*\{/.test(trimmed)) {
          inBlock = true; depth = 1; blockType = 'require-main';
          continue;
        }
        if (/\(?\s*function\s*\([^)]*\)\s*\{/.test(trimmed) &&
            (trimmed.startsWith('(') || trimmed.startsWith('!') || trimmed.startsWith(';') || trimmed.startsWith('+'))) {
          executableLines.push(line);
          inBlock = true; depth = 0; blockType = 'iife';
          const ob = (line.match(/\{/g) || []).length;
          const cb = (line.match(/\}/g) || []).length;
          depth = ob - cb;
          continue;
        }
        if (/^(?!import |export |const |let |var |class |function |\/\/|\/\*|\*\/)\S+\s*\(/.test(trimmed) && trimmed.endsWith(');')) {
          executableLines.push(line);
        }
      } else {
        executableLines.push(line);
        if (blockType === 'require-main' || blockType === 'iife') {
          depth += (line.match(/\{/g) || []).length - (line.match(/\}/g) || []).length;
          if (depth <= 0) {
            inBlock = false;
            executableLines.pop();
          }
        }
      }
    }

    return executableLines.length > 0 ? executableLines.join('\n').trim() : '';
  }

  // ===========================================================================
  // 工具方法
  // ===========================================================================

  wrapWithImports(code, imports) {
    if (!this.options.keepImports || imports.length === 0) return code;
    return imports.map(i => i.code).join('\n') + '\n\n' + code;
  }

  aggregateSmallItems(analysis) {
    const items = [...analysis.classes.filter(c => !c.isComponent), ...analysis.functions];
    if (items.length === 0) return null;

    const grouped = [];
    let current = { code: '', size: 0 };

    items.forEach(item => {
      if (current.size + item.size > MAX_SIZE && current.code) {
        grouped.push(current);
        current = { code: '', size: 0 };
      }
      current.code += item.code + '\n\n';
      current.size += item.size;
    });

    if (current.code) grouped.push(current);
    return this.wrapWithImports(grouped[0]?.code || '', analysis.imports);
  }

  toKebabCase(str) {
    return str.replace(/([a-z])([A-Z])/g, '$1-$2').replace(/([A-Z])([A-Z][a-z])/g, '$1-$2').toLowerCase();
  }

  // ===========================================================================
  // 报告
  // ===========================================================================

  printReport(success, originalSize) {
    console.log('\n============================================================');
    console.log('📊 拆分报告');
    console.log('============================================================');
    console.log(`📄 源文件: ${this.inputFile} (${(originalSize / 1024).toFixed(1)}KB)`);
    console.log(`📁 生成模块: ${this.modules.length} 个`);
    console.log(`💾 备份文件: ${this.backupPath ? path.basename(this.backupPath) : '未创建'}`);

    const violations = [];
    this.modules.forEach(mod => {
      const size = fs.statSync(mod.path).size;
      if (size > MAX_SIZE) violations.push({ name: mod.name, size });
    });

    console.log(`📏 所有文件 ≤19KB: ${violations.length === 0 ? '✅ 是' : '❌ 否'}`);

    if (violations.length > 0) {
      console.log('\n⚠️  超过限制的文件:');
      violations.forEach(v => console.log(`  - ${v.name}: ${(v.size / 1024).toFixed(1)}KB`));
    }

    console.log('============================================================');
    console.log('🎉 拆分完成!');
    console.log(`\n使用方式:`);
    console.log(`  import { ... } from './${this.outputDir}/index.js';`);
    console.log(`\n💡 如需恢复原始文件，参考备份: ${this.backupPath ? path.basename(this.backupPath) : 'N/A'}`);
    console.log('============================================================');
  }

  // ===========================================================================
  // CODE_INDEX.md 自动更新
  // ===========================================================================

  updateIndex() {
    const projectDir = path.dirname(path.resolve(this.inputFile));
    const indexScript = path.join(__dirname, '..', '..', 'python-file-splitter', 'scripts', 'generate_index.py');

    if (!fs.existsSync(indexScript)) {
      console.log('\n⚠️  generate_index.py not found, skipping index generation');
      return;
    }

    try {
      const pythonCmd = process.platform === 'win32' ? 'python' : 'python3';
      execSync(`${pythonCmd} "${indexScript}" "${projectDir}"`, {
        encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe']
      });
      console.log(`\n📑 CODE_INDEX.md updated: ${projectDir}/CODE_INDEX.md`);
    } catch (e) {
      console.log(`\n⚠️  Could not update CODE_INDEX.md: ${e.message}`);
    }
  }
}

// ============================================================================
// CLI 入口
// ============================================================================

function main() {
  const args = process.argv.slice(2);

  if (args.length === 0) {
    console.log(`
用法: node smart_split.js <输入文件> [输出目录] [选项]

选项:
  --maxSize <KB>    最大文件大小 (默认: 19KB)
  --framework       框架类型: react, vue, vanilla (默认: vanilla)
  --moduleType      模块类型: esm, cjs (默认: esm)
  --skipBackup      跳过备份 (不推荐)
  --force           强制拆分（包括压缩JS和图表绑定文件）

示例:
  node smart_split.js src/App.jsx components
  node smart_split.js utils/helpers.js lib --framework react
  node smart_split.js chart.js modules --force
    `);
    process.exit(1);
  }

  const inputFile = args[0];
  const outputDir = args[1] || 'modules';
  const options = {};

  args.slice(2).forEach(arg => {
    if (arg === '--skipBackup') options.skipBackup = true;
    if (arg === '--force') options.force = true;
    if (arg === '--framework' && args[args.indexOf(arg) + 1]) {
      options.framework = args[args.indexOf(arg) + 1];
    }
    if (arg === '--moduleType' && args[args.indexOf(arg) + 1]) {
      options.moduleType = args[args.indexOf(arg) + 1];
    }
  });

  const splitter = new JSFileSplitter(inputFile, outputDir, options);
  const success = splitter.split();

  process.exit(success ? 0 : 1);
}

// 导出类供模块使用
module.exports = { JSFileSplitter };

if (require.main === module) {
  main();
}
